backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow

display_url: https://ceus.vegas/ # This url will display in the top-right of the CMS
media_folder: "/static/imgs/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/static/media/imgs/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "pages"
    label: "Pages"
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: false
    slug: "{{slug}}"
    folder: "content/pages/"
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Rating (scale of 1-5)", name: "rating", widget: "number"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "services"
    label: "Services"
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: false
    slug: "{{slug}}"
    folder: "content/services/"
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}

